core/app/alarm/urls.py
from django.urls import include, path

from alarm.views.alarm_status_views import AlarmStatusUpdate, AlarmStatusCreate, AlarmStatusDetail, \
    AlarmScheduleUpdate, AlarmScheduleCreate, AlarmScheduleDetail
from camera.views.camera_motion_views import CameraMotionDetectedList, CameraMotionDetectedDetail
from camera.views.camera_roi_views import CameraROICreate, CameraROIUpdate, CameraROIList, CameraROIDelete
from alarm.views.alarm_status_views import AlarmHome
from alarm.views.schedule_range_views import AlarmScheduleRangeCreate, AlarmScheduleRangeDetail, AlarmScheduleRangeUpdate


app_name = 'alarm'


status_patterns = [
    path('<int:pk>/edit', AlarmStatusUpdate.as_view(), name='status-edit'),
    path('add', AlarmStatusCreate.as_view(), name='status-add'),
    path('<int:pk>', AlarmStatusDetail.as_view(), name='status-detail')
]


schedule_patterns = [
    path('<int:pk>/edit', AlarmScheduleUpdate.as_view(), name='schedule-edit'),
    path('add', AlarmScheduleCreate.as_view(), name='schedule-add'),
    path('<int:pk>', AlarmScheduleDetail.as_view(), name='schedule-detail')
]

roi_patterns = [
    path('', CameraROIList.as_view(), name='camera_roi-list'),
    path('<int:pk>/edit', CameraROIUpdate.as_view(), name='camera_roi-edit'),
    path('<int:pk>/delete', CameraROIDelete.as_view(), name='camera_roi-delete'),
    path('add', CameraROICreate.as_view(), name='camera_roi-add'),
]

motions_pattern = [
    path('', CameraMotionDetectedList.as_view(), name='camera_motion_detected-list'),
    path('<int:pk>', CameraMotionDetectedDetail.as_view(), name='camera_motion_detected-detail'),
]

absence_patterns = [
    path('add', AlarmScheduleRangeCreate.as_view(), name='absence-add'),
    path('<int:pk>', AlarmScheduleRangeDetail.as_view(), name='absence-detail'),
    path('<int:pk>/edit', AlarmScheduleRangeUpdate.as_view(), name='absence-edit')
]

urlpatterns = [
    path('', AlarmHome.as_view(), name='home'),
    path('', include(status_patterns)),
    path('schedule/', include(schedule_patterns)),
    path('absence/', include(absence_patterns)),
    path('camera_roi/', include(roi_patterns)),
    path('camera_motion/', include(motions_pattern)),
]

core/app/camera/urls.py
from django.urls import include, path

from camera.views import CameraHome
from camera.views.camera_motion_views import CameraMotionDetectedList, CameraMotionDetectedDetail
from camera.views.camera_roi_views import CameraROICreate, CameraROIDelete, CameraROIUpdate, CameraROIList
from camera.views.stream_views import stream_answer, CameraStreamDetail

app_name = 'camera'

roi_patterns = [
    path('', CameraROIList.as_view(), name='camera_roi-list'),
    path('<int:pk>/edit', CameraROIUpdate.as_view(), name='camera_roi-edit'),
    path('<int:pk>/delete', CameraROIDelete.as_view(), name='camera_roi-delete'),
    path('add', CameraROICreate.as_view(), name='camera_roi-add'),
]

motions_pattern = [
    path('', CameraMotionDetectedList.as_view(), name='camera_motion_detected-list'),
    path('<int:pk>', CameraMotionDetectedDetail.as_view(), name='camera_motion_detected-detail'),
]

streaming_pattern = [
]

urlpatterns = [
    path('', CameraHome.as_view(), name='home'),
    path('<int:pk>/stream', CameraStreamDetail.as_view(), name='stream-detail'),
    path('<int:pk>/stream/flux.jpg', stream_answer, name='camera_stream'),

    path('roi/', include(roi_patterns)),
    path('motion/', include(motions_pattern)),
]

core/app/hello_django/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

from hello_django.views import HomeView, ConfigurationView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path(r'admin/', admin.site.urls),
    path('device/', include('devices.urls', namespace='device')),
    path('alarm/', include('alarm.urls', namespace='alarm')),
    path('camera/', include('camera.urls', namespace='camera')),
    path('accounts/', include('account.urls')),
    path('setup/', include('setup.urls', namespace='setup')),
    path('configuration/', ConfigurationView.as_view(), name='configuration'),
    path('house/', include('house.urls', namespace='house')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # https://docs.djangoproject.com/en/3.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/app/camera/models.py
from django.db import models

from devices.models import Device


class CameraROI(models.Model):
    device = models.OneToOneField(Device, on_delete=models.PROTECT)

    """
    We save the picture where the user defined the ROI.
    This could be useful to check if the camera moves to let know the user
    because the ROI could become wrong.
    """
    define_picture = models.ImageField()


class CameraRectangleROIManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(disabled=False)


class CameraRectangleROI(models.Model):
    class Meta:
        default_manager_name = 'objects'

    objects = models.Manager()
    actives = CameraRectangleROIManager()

    # ? We might rework the max_digits & decimal_places here
    # I didn't really know what to put here. Seems good but may not be optimized.

    x = models.DecimalField(max_digits=8, decimal_places=4)
    y = models.DecimalField(max_digits=8, decimal_places=4)
    w = models.DecimalField(max_digits=8, decimal_places=4)
    h = models.DecimalField(max_digits=8, decimal_places=4)

    disabled = models.BooleanField(default=False)

    camera_roi = models.ForeignKey(CameraROI, on_delete=models.CASCADE)


class CameraMotionDetected(models.Model):
    class Meta:
        ordering = ('-motion_started_at',)

    event_ref = models.UUIDField(unique=True)

    motion_started_at = models.DateTimeField()
    motion_ended_at = models.DateTimeField(blank=True, null=True)

    closed_by_system = models.BooleanField(default=False)

    device = models.ForeignKey(Device, on_delete=models.PROTECT, related_name='camera_motions')
    in_rectangle_roi = models.ManyToManyField(CameraRectangleROI, blank=True)

    def __repr__(self) -> str:
        return f'{self.event_ref} device={self.device} start={self.motion_started_at} end={self.motion_ended_at} closed_by_system={self.closed_by_system}'

class CameraMotionDetectedBoundingBox(models.Model):
    """
    This is given by Tensorflow, they are bounding boxes around an object.
    This coordinates have been rescaled on the picture, they are not relatives ([0;1]).
    """
    x = models.IntegerField()
    y = models.IntegerField()
    w = models.IntegerField()
    h = models.IntegerField()

    score = models.FloatField(blank=True, null=True)

    camera_motion_detected = models.ForeignKey(CameraMotionDetected, on_delete=models.CASCADE)


class CameraMotionDetectedPicture(models.Model):
    event_ref = models.UUIDField(unique=True)

    created_at = models.DateTimeField(auto_now_add=True)

    motion_started_picture = models.ImageField()
    motion_ended_picture = models.ImageField(blank=True, null=True)

    device = models.ForeignKey(Device, on_delete=models.PROTECT, related_name='camera_motions_pictures')

class CameraMotionVideo(models.Model):
    event_ref = models.UUIDField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    number_records = models.PositiveIntegerField(default=1)
    last_record = models.DateTimeField()
    is_merged = models.BooleanField(default=False)

    device = models.ForeignKey(Device, on_delete=models.PROTECT, related_name='camera_motions_videos')

    def __repr__(self) -> str:
        return f'{self.event_ref} device={self.device} created_at={self.created_at} last_record={self.last_record} is_merged={self.is_merged}'

    def __str__(self):
        return f'{self.event_ref} - {self.created_at}'

core/app/camera/forms.py
from django import forms
from django.forms import modelformset_factory

from camera.models import CameraRectangleROI, CameraROI


class CameraROIForm(forms.ModelForm):
    class Meta:
        model = CameraROI
        exclude = ('define_picture',)


class CameraROIUpdateForm(forms.ModelForm):
    class Meta:
        model = CameraROI
        exclude = ('define_picture', 'device')


class CameraRectangleROIForm(forms.ModelForm):

    class Meta:
        model = CameraRectangleROI
        fields = '__all__'


CameraRectangleROIFormSet = modelformset_factory(CameraRectangleROI, exclude=('camera_roi',))

core/app/camera/views/camera_motion_views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from camera.models import CameraMotionDetected, CameraMotionDetectedPicture
from utils.json.encoders import DecimalEncoder


class CameraMotionDetectedList(LoginRequiredMixin, ListView):
    template_name = 'camera/camera_motion_detected_list.html'
    queryset = CameraMotionDetected.objects.order_by('-motion_started_at')
    context_object_name = 'motions'


class CameraMotionDetectedDetail(LoginRequiredMixin, DetailView):
    model = CameraMotionDetected
    template_name = 'camera/camera_motion_detected_detail.html'
    context_object_name = 'motion'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        camera_motion_detected: CameraMotionDetected = context[self.context_object_name]

        camera_roi = list(camera_motion_detected.in_rectangle_roi.all().values())
        context['json_camera_roi'] = json.dumps(camera_roi, cls=DecimalEncoder)

        bounding_boxes = camera_motion_detected.cameramotiondetectedboundingbox_set.all()
        bounding_boxes_plain = list(bounding_boxes.values())
        context['bounding_boxes'] = bounding_boxes
        context['json_bounding_boxes'] = json.dumps(bounding_boxes_plain, cls=DecimalEncoder)

        try:
            context['picture'] = CameraMotionDetectedPicture.objects.get(event_ref=camera_motion_detected.event_ref)
        except CameraMotionDetectedPicture.DoesNotExist:
            context['picture'] = None

        return context

core/app/camera/views/camera_roi_views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.urls import reverse_lazy
from django.views.generic import UpdateView, ListView
from django.views.generic.edit import FormView, DeleteView
from django.forms.models import model_to_dict

from camera.forms import CameraROIForm, CameraROIUpdateForm, CameraRectangleROIFormSet
from camera.models import CameraROI, CameraRectangleROI, CameraMotionDetectedPicture
from utils.django.json_view import JsonableResponseMixin
from utils.json.encoders import DecimalEncoder


class CameraROIList(LoginRequiredMixin, ListView):
    queryset = CameraROI.objects.all()
    template_name = 'camera/camera_roi_list.html'
    context_object_name = 'rois'


class CameraROIDelete(LoginRequiredMixin, DeleteView):
    model = CameraROI
    success_url = reverse_lazy('camera:camera_roi-list')


class CameraROIUpdate(LoginRequiredMixin, JsonableResponseMixin, UpdateView):
    template_name = 'camera/camera_roi_form.html'
    model = CameraROI
    form_class = CameraROIUpdateForm
    success_url = reverse_lazy('camera:camera_roi-list')


    def get_context_data(self, **kwargs):
        context = super(CameraROIUpdate, self).get_context_data(**kwargs)
        camera_roi = context['cameraroi']

        camera_roi_rectangles = list(CameraRectangleROI.actives.filter(camera_roi=camera_roi).values())
        camera_roi_rectangles = json.dumps(camera_roi_rectangles, cls=DecimalEncoder)

        context['camera_rectangle_roi_formset'] = CameraRectangleROIFormSet(queryset=CameraRectangleROI.objects.none())

        context['camera_roi_rectangles'] = camera_roi_rectangles

        motion_picture = CameraMotionDetectedPicture.objects.last()
        context['motion_picture'] = motion_picture.picture

        return context

    def form_valid(self, form):
        formset = CameraRectangleROIFormSet(self.request.POST)

        camera_roi: CameraROI = form.instance

        if formset.is_valid():
            with transaction.atomic():
                form.save(commit=False)

                camera_roi_pk = camera_roi.pk
                CameraRectangleROI.objects.filter(camera_roi=camera_roi_pk, disabled=False).update(disabled=True)

                instances = formset.save(commit=False)
                for instance in instances:
                    instance.camera_roi_id = camera_roi_pk

                formset.save()
                form.save()

            return super().form_valid(form)

        # @TODO: form no valid, what do we do?
        return super().form_invalid(formset.errors)


class CameraROICreate(LoginRequiredMixin, JsonableResponseMixin, FormView):
    template_name = 'camera/camera_roi_form.html'
    model = CameraROI
    form_class = CameraROIForm
    success_url = reverse_lazy('camera:camera_roi-list')


    def get_context_data(self, **kwargs):
        context = super(CameraROICreate, self).get_context_data(**kwargs)

        context['camera_rectangle_roi_formset'] = CameraRectangleROIFormSet()

        motion_picture = CameraMotionDetectedPicture.objects.last()
        context['motion_picture'] = motion_picture.picture

        return context


    def form_invalid(self, form):
        return super().form_invalid(form)


    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        formset = CameraRectangleROIFormSet(self.request.POST)

        camera_roi: CameraROI = form.instance

        if formset.is_valid():
            with transaction.atomic():
                motion_picture = CameraMotionDetectedPicture.objects.last()
                form.instance.define_picture = motion_picture.motion_started_picture
                form.save()

                camera_roi_pk = form.instance.pk

                instances = formset.save(commit=False)
                for instance in instances:
                    instance.camera_roi_id = camera_roi_pk

                formset.save()

            return super().form_valid(form)

        # @TODO: form no valid, what do we do?
        return super().form_invalid(formset.errors)

core/app/camera/views/stream_views.py
import io
from typing import Tuple

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import StreamingHttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView

from alarm.models import AlarmStatus
from camera.messaging import CameraMessaging, camera_messaging_factory, CameraData
from utils.mqtt import mqtt_factory, MQTT


class HttpStreamMQTT:
    BOUNDARY = 'frame'

    def __init__(self, alarm: AlarmStatus):
        self._picture = None
        self._alarm = alarm
        self._mqtt, self._camera_messaging = self._mqtt_init()
        self._consecutive_failures = 0

    def _mqtt_init(self) -> Tuple[MQTT, CameraMessaging]:
        mqtt = mqtt_factory()
        mqtt.client.subscribe(f'camera/stream/{self._alarm.device.device_id}', qos=0)
        mqtt.client.message_callback_add(f'camera/stream/{self._alarm.device.device_id}', self._frame_receiver)

        camera_messaging = camera_messaging_factory(mqtt)
        camera_messaging.publish_status(self._alarm.device.device_id, True, CameraData(stream=True))

        return mqtt, camera_messaging

    def _frame_receiver(self, _client, _userdata, message):
        self._picture = io.BytesIO(message.payload).getvalue()

    def produce(self):
        # ~25 frame per seconds, if it does not receive any frame for ~8s it stops the loop
        # and thus stop the stream.
        while True and self._consecutive_failures < 25*8:
            self._mqtt.client.loop()
            if self._picture:
                self._consecutive_failures = 0
                yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + self._picture + b'\r\n\r\n')
                self._picture = None
            else:
                self._consecutive_failures += 1

    def __del__(self):
        # query because AlarmStatus could have turned off during the stream.
        alarm = AlarmStatus.objects.get(pk=self._alarm.pk)

        if alarm.running is False:
            self._camera_messaging.publish_status(self._alarm.device.device_id, False, CameraData(stream=False))
        else:
            self._camera_messaging.publish_status(self._alarm.device.device_id, True, CameraData(stream=False))

class CameraStreamingHttpResponse(StreamingHttpResponse):
    def __init__(self, stream: HttpStreamMQTT, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._stream = stream

    def close(self):
        super().close()
        # we need to manually delete the object to stop the background thread
        # and close mqtt connections that listen for frames.
        self._stream.__del__()


def stream_answer(_request, pk):
    alarm = get_object_or_404(AlarmStatus, id=pk)
    stream = HttpStreamMQTT(alarm)

    return CameraStreamingHttpResponse(stream, stream.produce(), content_type=f"multipart/x-mixed-replace;boundary=frame")


class CameraStreamDetail(LoginRequiredMixin, DetailView):
    model = AlarmStatus
    template_name = 'camera/camera_stream.html'

    context_object_name = 'camera'

core/app/templates/camera/camera_motion_detected_detail.html
{% extends '_layout.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Camera motion detail' %}
{% endblock title %}


{% block body %}
    <main class="l-container">
        <section class="l-section">
            <div class="l-row">
                <div class="copy variant--box variant--content">
                    <div class="copy__body l-stack">
                        <div class="l-stack-bottom-separator">
                            <h3 class="h5">{% trans 'Device information' %}</h3>
                        </div>
                        <p class="flex items-center">
                            {% svg_icon 'location' %} <span class="l-ml1">{{ motion.device.location }}</span>
                        </p>
                        <p class="flex items-center">
                            {% svg_icon 'server' %} <span class="l-ml1">{% firstof motion.device.name alarm.device.device_type.type %}</span>
                        </p>
                    </div>
                </div>
                <div class="copy variant--box variant--content">
                    <div class="copy__body l-stack">
                        <div class="l-stack-bottom-separator">
                            <h3 class="h5">{% trans 'Motion information' %}</h3>
                        </div>
                        <ul>
                            <p>{{ motion.motion_started_at }} to {{ motion.motion_ended_at }}</p>
                            {% for bounding_box in bounding_boxes %}
                                <p>Score: {{bounding_box.score}}</p>
                            {% endfor %}
                        </ul>
                        {% if picture %}
                        <p>{% trans 'Picture taken when people was detected.' %}</p>
                           <motion-picture
                                   data-picture="{{ picture.motion_started_picture.url }}"
                                   data-bounding-boxes="{{ json_bounding_boxes }}"
                                   data-camera-boxes="{{ json_camera_roi }}"
                           ></motion-picture>
                         {% if picture.motion_ended_picture %}
                            <p>{% trans 'Picture taken when people left.' %}</p>
                            <img src="{{picture.motion_ended_picture.url}}" alt="{% trans 'Motion ended picture.' %}"/>
                          {% else %}
                            <p>{% trans 'No picture was taken when people left. Could happens when the device linked to the camera turn off before people left.' %}</p>
                          {% endif %}
                        {% else %}
                            <p>{% trans 'The system does not have any picture for this event.' %}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
    </main>

    {% assets 'entrypoints/motion-detected.js' %}

{% endblock body %}

core/app/templates/camera/camera_motion_detected_list.html
{% extends '_layout.html' %}

{% load i18n %}

{% block title %}
    Camera motion list
{% endblock title %}

{% block body %}
    <main class="l-container">
        <section class="l-section l-row">
            <h2 class="h5">{% trans 'List of camera motion detected' %}</h2>
            {% include 'partials/_camera_motion_list.html' %}
        </section>
    </main>
{% endblock body %}

core/app/templates/camera/camera_roi_form.html
{% extends '_layout.html' %}

{% block header %}
    <h1 class="h3">Alarm ROI</h1>
{% endblock header %}

{% block body %}
    <main class="l-container">
        <div class="box">
            <div class="box__body">
                <form action="" method="post" class="form-ajax">
                    {{ csrf_input }}
                    {{ form }}
                    {{ camera_rectangle_roi_formset.management_form }}

                    <div id="container">
                        <canvas id="imageView" width="400" height="300"></canvas>
                    </div>

                    <button type="submit">Submit</button>
                    <button type="button" id="clean">Clean</button>
                </form>
            </div>
        </div>
    </main>

    <script>
        const FILE_URL = "{{ motion_picture.url }}"
        {% if camera_roi_rectangles %}
            window.RECTANGLES = JSON.parse({{ camera_roi_rectangles | safe }})
        {% endif %}
    </script>

    {% assets 'entrypoints/draw-shape.js' %}
{% endblock body %}

core/app/templates/camera/camera_roi_list.html
{% extends '_layout.html' %}

{% block header %}
    <h1 class="h3">Alarm roi list</h1>

{% endblock header %}

{% block body %}
    <main class="l-container">
        <div class="box">
            <div class="box__body">
                <h2>Alarm roi list</h2>
                <a href="{% url 'camera:camera_roi-add' %}">Add a new ROI to a camera</a>
                <ul>
                    {% for roi in rois %}
                        <li>
                            <a href="{% url 'camera:camera_roi-edit' roi.pk %}">{{ roi }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </main>

{% endblock body %}

core/app/templates/camera/camera_stream.html
{% extends '_layout.html' %}
{% load i18n %}

{% block title %}
    Camera stream
{% endblock title %}


{% block body %}
    <main class="l-container">
        <section class="l-section">
            <div class="l-row">
                <div class="copy variant--box variant--content">
                    <div class="copy__body l-stack">
                        <div class="l-stack-bottom-separator">
                            <h3 class="h5">{% trans 'Camera stream' %}</h3>
                        </div>
                        <p class="flex items-center">
                            {% svg_icon 'location' %} <span class="l-ml1">{{ camera.device.location }}</span>
                        </p>
                        <img src="{% url 'camera:camera_stream' camera.pk %}" alt="{% trans 'Live stream' %}" />
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

core/app/templates/camera/cameraroi_confirm_delete.html
{% extends '_layout.html' %}

{% block header %}
    <h1 class="h3">Alarm ROI delete</h1>
{% endblock header %}

{% block body %}
    <main class="l-container">
        <div class="box">
            <div class="box__body">
                <form method="post">
                    {{ csrf_input }}
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                    <input type="submit" value="Confirm">
                </form>
            </div>
        </div>
    </main>

{% endblock body %}

core/app/templates/camera/home.html
{% extends '_layout.html' %}
{% load i18n %}

{% block body %}
    <div class="l-container">
        <div class="l-section l-row">
            {% include 'partials/_camera_list.html' %}
        </div>
    </div>
{% endblock body %}