core/app/alarm/urls.py
from django.urls import include, path

from alarm.views.alarm_status_views import AlarmStatusUpdate, AlarmStatusCreate, AlarmStatusDetail, \
    AlarmScheduleUpdate, AlarmScheduleCreate, AlarmScheduleDetail
from camera.views.camera_motion_views import CameraMotionDetectedList, CameraMotionDetectedDetail
from camera.views.camera_roi_views import CameraROICreate, CameraROIUpdate, CameraROIList, CameraROIDelete
from alarm.views.alarm_status_views import AlarmHome
from alarm.views.schedule_range_views import AlarmScheduleRangeCreate, AlarmScheduleRangeDetail, AlarmScheduleRangeUpdate


app_name = 'alarm'


status_patterns = [
    path('<int:pk>/edit', AlarmStatusUpdate.as_view(), name='status-edit'),
    path('add', AlarmStatusCreate.as_view(), name='status-add'),
    path('<int:pk>', AlarmStatusDetail.as_view(), name='status-detail')
]


schedule_patterns = [
    path('<int:pk>/edit', AlarmScheduleUpdate.as_view(), name='schedule-edit'),
    path('add', AlarmScheduleCreate.as_view(), name='schedule-add'),
    path('<int:pk>', AlarmScheduleDetail.as_view(), name='schedule-detail')
]

roi_patterns = [
    path('', CameraROIList.as_view(), name='camera_roi-list'),
    path('<int:pk>/edit', CameraROIUpdate.as_view(), name='camera_roi-edit'),
    path('<int:pk>/delete', CameraROIDelete.as_view(), name='camera_roi-delete'),
    path('add', CameraROICreate.as_view(), name='camera_roi-add'),
]

motions_pattern = [
    path('', CameraMotionDetectedList.as_view(), name='camera_motion_detected-list'),
    path('<int:pk>', CameraMotionDetectedDetail.as_view(), name='camera_motion_detected-detail'),
]

absence_patterns = [
    path('add', AlarmScheduleRangeCreate.as_view(), name='absence-add'),
    path('<int:pk>', AlarmScheduleRangeDetail.as_view(), name='absence-detail'),
    path('<int:pk>/edit', AlarmScheduleRangeUpdate.as_view(), name='absence-edit')
]

urlpatterns = [
    path('', AlarmHome.as_view(), name='home'),
    path('', include(status_patterns)),
    path('schedule/', include(schedule_patterns)),
    path('absence/', include(absence_patterns)),
    path('camera_roi/', include(roi_patterns)),
    path('camera_motion/', include(motions_pattern)),
]

core/app/camera/urls.py
from django.urls import include, path

from camera.views import CameraHome
from camera.views.camera_motion_views import CameraMotionDetectedList, CameraMotionDetectedDetail
from camera.views.camera_roi_views import CameraROICreate, CameraROIDelete, CameraROIUpdate, CameraROIList
from camera.views.stream_views import stream_answer, CameraStreamDetail

app_name = 'camera'

roi_patterns = [
    path('', CameraROIList.as_view(), name='camera_roi-list'),
    path('<int:pk>/edit', CameraROIUpdate.as_view(), name='camera_roi-edit'),
    path('<int:pk>/delete', CameraROIDelete.as_view(), name='camera_roi-delete'),
    path('add', CameraROICreate.as_view(), name='camera_roi-add'),
]

motions_pattern = [
    path('', CameraMotionDetectedList.as_view(), name='camera_motion_detected-list'),
    path('<int:pk>', CameraMotionDetectedDetail.as_view(), name='camera_motion_detected-detail'),
]

streaming_pattern = [
]

urlpatterns = [
    path('', CameraHome.as_view(), name='home'),
    path('<int:pk>/stream', CameraStreamDetail.as_view(), name='stream-detail'),
    path('<int:pk>/stream/flux.jpg', stream_answer, name='camera_stream'),

    path('roi/', include(roi_patterns)),
    path('motion/', include(motions_pattern)),
]

core/app/devices/urls.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import include, path
from django.views.generic import DetailView
from devices.models import Device

app_name = 'device'

class DeviceCameraMotions(LoginRequiredMixin, DetailView):
    model = Device
    template_name = 'device/device_camera_motion_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

urlpatterns = [
    path('<int:pk>/camera/motions', DeviceCameraMotions.as_view(), name='camera-motion-list')
]

core/app/hello_django/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

from hello_django.views import HomeView, ConfigurationView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path(r'admin/', admin.site.urls),
    path('device/', include('devices.urls', namespace='device')),
    path('alarm/', include('alarm.urls', namespace='alarm')),
    path('camera/', include('camera.urls', namespace='camera')),
    path('accounts/', include('account.urls')),
    path('setup/', include('setup.urls', namespace='setup')),
    path('configuration/', ConfigurationView.as_view(), name='configuration'),
    path('house/', include('house.urls', namespace='house')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # https://docs.djangoproject.com/en/3.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/app/templates/partials/_alarm_list.html
{% load i18n %}

<div class="l-row alarms">
    {% for alarm in alarms %}
        <div class="copy variant--box variant--content">
            <div class="copy__body l-stack">
                {% with see_schedules=True %}
                    {% include 'partials/_alarm_status_info.html' %}
                {% endwith %}
            </div>
            <div class="copy__footer flex items-end">
                <div class="copy__cta flex flex-1 justify-between">
                    <a class="btn-secondary" href="{% url 'alarm:status-edit' alarm.pk %}">{% trans 'Update' %}</a>
                    <a class="btn-secondary" href="{% url 'alarm:status-detail' alarm.pk %}">
                        {% trans 'See more' %}
                        {% svg_icon 'chevron-right' 'right icon-tx' %}
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

core/app/templates/partials/_alarm_schedule_info.html
{% load i18n %}

<div class="copy variant--content variant--box">
    <div class="copy__body l-stack">

        {% if box_title %}
            <div class="l-stack-bottom-separator">
                <h3 class="h5">{% trans box_title %}</h3>
            </div>
        {% endif %}

        <p class="flex items-center">
            {% svg_icon 'shield' %}
            <span class="l-ml1">L'alarme s'allume de {{ schedule.start_time }} à {{ schedule.end_time }}</span>
        </p>
        <div class="alarm-schedule-days">
            {% for day in DAYS_OF_WEEK %}
                <div class="badge">
                    {% if schedule|get_obj_attr:day %}
                        <span class="badge-active-status"></span>
                    {% else %}
                        <span class="badge-unactive-status"></span>
                    {% endif %}
                    <span>{{ day }}</span>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="copy__footer">
        <div class="copy__cta">
            <a class="btn-secondary" href="{% url 'alarm:schedule-edit' schedule.pk %}">{% trans 'Update' %}</a>
            {% if see_more %}
                <a class="btn-primary" href="{% url 'alarm:schedule-detail' schedule.pk %}">{% trans 'See more' %} {% svg_icon 'chevron-right' %}</a>
            {% endif %}
        </div>
    </div>
</div>

core/app/templates/partials/_alarm_status_info.html
{% load i18n %}

<p class="flex items-center">
    {% if alarm.running %}
        {% svg_icon 'shield' %} <span class="l-ml1">Alarme activée</span>
    {% else %}
        {% svg_icon 'shield-exclamation' %} <span class="l-ml1">Alarme désactivée</span>
    {% endif %}
</p>
<p class="flex items-center">
    {% svg_icon 'location' %} <span class="l-ml1">{{ alarm.device.location }}</span>
</p>
<p class="flex items-center">
    {% svg_icon 'server' %} <span class="l-ml1">{% firstof alarm.device.name alarm.device.device_type.type %}</span>
</p>

<p class="flex items-center">
    {% svg_icon 'camera' %}
    <a class="l-ml1" href="{% url 'camera:stream-detail' alarm.pk %}">{% trans 'Live stream' %}</a>
</p>

{% if alarm.alarm_schedules.all %}
    <div class="flex items-center">
        {% svg_icon 'clock' %}
        <div class="flex flex-col l-ml1">
            {% if alarm.running == False and alarm.get_next_on_schedule %}
                <span>L'alarme va s'allumer à {{ alarm.get_next_on_schedule.start_time }}</span>
            {% endif %}

            {% if alarm.running and alarm.get_next_off_schedule %}
                <span>L'alarme va s'éteindre à {{ alarm.get_next_off_schedule.end_time }}</span>
            {% endif %}

            {% if see_schedules is not False %}
                <a href="{% url 'alarm:status-detail' alarm.pk %}">Voir les plannings</a>
            {% endif %}
        </div>
    </div>
{% else %}
    <div class="flex items-center">
        {% svg_icon 'clock' %}
        <div class="flex flex-col l-ml1">
            <a href="{% url 'alarm:schedule-add'%}">{% trans "Create schedule" %}</a>
        </div>
    </div>
{% endif %}

{% if alarm.device.camera_motions.all %}
    <div class="flex items-center">
        {% svg_icon 'eye' %}
        <div class="flex flex-col l-ml1">
            <a href="{% url 'device:camera-motion-list' alarm.device.pk %}">See linked motions</a>
        </div>
    </div>
{% endif %}

core/app/templates/partials/_camera_list.html
{% load i18n %}

<div class="l-row alarms">
    {% for camera in cameras %}
        <div class="copy variant--box variant--content">
            <div class="copy__body l-stack">
                <p class="flex items-center">
                    {% svg_icon 'location' %} <span class="l-ml1">{{ camera.device.location }}</span>
                </p>
            </div>
            <div class="copy__footer flex items-end">
                <div class="copy__cta">
                    <a class="btn-secondary" href="{% url 'camera:stream-detail' camera.pk %}">{% trans 'Live stream' %}</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

core/app/templates/partials/_camera_motion_list.html
{% load i18n %}

<div class="l-row">
    {% for motion in motions %}
        <div class="copy variant--box variant--content">
            <div class="copy__body l-stack">
                <p>
                    {{ motion.pk }} {{ motion.motion_started_at }} to {{ motion.motion_ended_at }}
                    {% if motion.closed_by_system %}
                        The event has been closed automatically by the system.
                    {% endif %}
                </p>
            </div>
            <div class="copy__footer flex items-end">
                <div class="copy__cta">
                    <a class="btn-primary" href="{% url 'camera:camera_motion_detected-detail' motion.pk %}">{% trans 'See more' %}</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

core/app/templates/partials/_form.html
{# Partials to be included inside a <form> HTMLElement #}
{# Include logic to render necessary inputs, errors and so on. #}

{% csrf_token %}
{# Include the hidden fields #}
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}

{% if form.non_field_errors %}
    <div class="form-errors">
        {% svg_icon 'exclamation' %}
        <ul>
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{# Include the visible fields #}
{% for field in form.visible_fields %}
    {% if field.field.widget.input_type == 'checkbox' %}
        <div class="form-group form-switch">
    {% else %}
        <div class="form-group">
    {% endif %}
            <div class="label-wrapper">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
            </div>

            <div class="field-wrapper">
                {{ field }}

                {% if field.field.widget.input_type == 'checkbox' %}
                    <span class="switch"></span>
                {% endif %}

                {% if field.help_text %}
                    <p class="help-text">{{ field.help_text|safe }}</p>
                {% endif %}

                {% if field.errors %}
                    <div class="form-errors">
                        {% svg_icon 'exclamation' %}
                        <ul>
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
{% endfor %}

core/app/templates/partials/_form_actions.html
<div class="copy__cta">
    <input type="submit" class="btn-primary" name="submit" value="{{ btn_text }}" />
</div>

core/app/templates/partials/_topbar.html
{% load i18n %}

<div class="topbar">
    <nav class="topbar__nav l-container" role="navigation" aria-label="{% trans 'Main navigation' %}">
        <ul class="topbar__nav__list">
            <li>
                <a class="copy__body" href="{% url 'home' %}">{% svg_icon 'home' %} {% trans "Home" %}</a>
            </li>
            <li>
                <a class="copy__body" href="{% url 'alarm:home' %}">{% svg_icon 'shield' %} {% trans "Alarms" %}</a>
            </li>
            <li>
                <a class="copy__body" href="{% url 'camera:home' %}">{% svg_icon 'camera' %}{% trans "Cameras" %}</a>
            </li>
            <li>
                <a class="copy__body" href="{% url 'configuration' %}">{% svg_icon 'cog' %}{% trans "Configuration" %}</a>
            </li>
        </ul>

        <ul class="topbar__nav__side">
            {% if request.user.is_authenticated %}
                <li>
                    <p class="copy__body">{{ request.user.first_name }}</p>
                </li>
                <li>
                    <a class="copy__body" href="{% url 'logout' %}">Logout <span class="l-ml1">{% svg_icon 'logout' %}</span></a>
                </li>
            {% else %}
                <li>
                    <a class="copy__body" href="{% url 'login' %}">{% trans 'Login' %}</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>