core/app/alarm/urls.py
from django.urls import include, path

from alarm.views.alarm_status_views import AlarmStatusUpdate, AlarmStatusCreate, AlarmStatusDetail, \
    AlarmScheduleUpdate, AlarmScheduleCreate, AlarmScheduleDetail
from camera.views.camera_motion_views import CameraMotionDetectedList, CameraMotionDetectedDetail
from camera.views.camera_roi_views import CameraROICreate, CameraROIUpdate, CameraROIList, CameraROIDelete
from alarm.views.alarm_status_views import AlarmHome
from alarm.views.schedule_range_views import AlarmScheduleRangeCreate, AlarmScheduleRangeDetail, AlarmScheduleRangeUpdate


app_name = 'alarm'


status_patterns = [
    path('<int:pk>/edit', AlarmStatusUpdate.as_view(), name='status-edit'),
    path('add', AlarmStatusCreate.as_view(), name='status-add'),
    path('<int:pk>', AlarmStatusDetail.as_view(), name='status-detail')
]


schedule_patterns = [
    path('<int:pk>/edit', AlarmScheduleUpdate.as_view(), name='schedule-edit'),
    path('add', AlarmScheduleCreate.as_view(), name='schedule-add'),
    path('<int:pk>', AlarmScheduleDetail.as_view(), name='schedule-detail')
]

roi_patterns = [
    path('', CameraROIList.as_view(), name='camera_roi-list'),
    path('<int:pk>/edit', CameraROIUpdate.as_view(), name='camera_roi-edit'),
    path('<int:pk>/delete', CameraROIDelete.as_view(), name='camera_roi-delete'),
    path('add', CameraROICreate.as_view(), name='camera_roi-add'),
]

motions_pattern = [
    path('', CameraMotionDetectedList.as_view(), name='camera_motion_detected-list'),
    path('<int:pk>', CameraMotionDetectedDetail.as_view(), name='camera_motion_detected-detail'),
]

absence_patterns = [
    path('add', AlarmScheduleRangeCreate.as_view(), name='absence-add'),
    path('<int:pk>', AlarmScheduleRangeDetail.as_view(), name='absence-detail'),
    path('<int:pk>/edit', AlarmScheduleRangeUpdate.as_view(), name='absence-edit')
]

urlpatterns = [
    path('', AlarmHome.as_view(), name='home'),
    path('', include(status_patterns)),
    path('schedule/', include(schedule_patterns)),
    path('absence/', include(absence_patterns)),
    path('camera_roi/', include(roi_patterns)),
    path('camera_motion/', include(motions_pattern)),
]

core/app/hello_django/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

from hello_django.views import HomeView, ConfigurationView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path(r'admin/', admin.site.urls),
    path('device/', include('devices.urls', namespace='device')),
    path('alarm/', include('alarm.urls', namespace='alarm')),
    path('camera/', include('camera.urls', namespace='camera')),
    path('accounts/', include('account.urls')),
    path('setup/', include('setup.urls', namespace='setup')),
    path('configuration/', ConfigurationView.as_view(), name='configuration'),
    path('house/', include('house.urls', namespace='house')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # https://docs.djangoproject.com/en/3.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/app/alarm/models.py
import uuid

from django.utils import timezone
from django.db import models
from django_celery_beat.models import PeriodicTask, CrontabSchedule
from alarm.business.alarm_schedule import get_next_off_schedule, get_next_on_schedule, get_device_next_off_schedule, \
    get_device_next_on_schedule
from devices.models import Device
from django.db import transaction
from django.urls import reverse


class Ping(models.Model):
    device_id = models.CharField(max_length=8)
    service_name = models.CharField(max_length=100)

    # it's possible that a service never sent any ping.
    last_update = models.DateTimeField(default=None, blank=True, null=True)

    consecutive_failures = models.IntegerField(default=0)
    failures = models.IntegerField(default=0)

    class Meta:
        unique_together = ['device_id', 'service_name']

    def __str__(self):
        return f'Service {self.service_name} on device {self.device_id} last ping at {self.last_update}'

class AlarmStatusManager(models.Manager):
    def with_device_and_location(self):
        return self.select_related('device', 'device__location')

class AlarmStatus(models.Model):
    class Meta:
        verbose_name = 'alarm status'
        verbose_name_plural = 'alarm statuses'

    objects = AlarmStatusManager()

    running = models.BooleanField(
        help_text='Either or not the alarm is running on the device. If it runs, it monitor the device camera to react if a danger is recognized.',
        default=False
    )

    device = models.OneToOneField(
        Device, on_delete=models.CASCADE,
        help_text="The device that is controlled by the alarm. If you do not find the desired device, it means that an alarm is already linked to it."
    )

    is_dumb = models.BooleanField(
        default=True,
        help_text='Either or not the device is dumb, which means it runs the dumb camera software. Typically used for low-end devices such as RaspberryPi zero, esp...'
    )

    def __str__(self):
        return f'Status is {self.running} for {self.device}'

    def get_next_off_schedule(self):
        return get_device_next_off_schedule(timezone.now(), self.device.pk)

    def get_next_on_schedule(self):
        return get_device_next_on_schedule(timezone.now(), self.device.pk)

    def get_absolute_url(self):
        return reverse('alarm:status-detail', args=[str(self.id)])


class HTTPAlarmStatus(AlarmStatus):
    user = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    endpoint = models.URLField()


class AlarmScheduleManager(models.Manager):
    # @TODO: could be useless to have this method here.
    def get_next_off(self):
        return get_next_off_schedule(timezone.now(), self)

    # @TODO: could be useless to have this method here.
    def get_next_on(self):
        return get_next_on_schedule(timezone.now(), self)


class AlarmScheduleDateRange(models.Model):
    datetime_start = models.DateTimeField()
    datetime_end = models.DateTimeField(blank=True, null=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)

    turn_on_task = models.OneToOneField(
            PeriodicTask,
            editable=False,
            blank=True,
            null=True,
            on_delete=models.PROTECT,
            related_name='alarm_schedule_date_range_on')

    turn_off_task = models.OneToOneField(
            PeriodicTask,
            editable=False,
            blank=True,
            null=True,
            on_delete=models.PROTECT,
            related_name='alarm_schedule_date_range_off')


class AlarmSchedule(models.Model):
    objects = AlarmScheduleManager()

    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)

    start_time = models.TimeField(
        help_text='When the alarm should start to monitor if a danger is recognized to react.'
    )
    end_time = models.TimeField(
        help_text='When the alarm should stop the monitoring and thus it will not react to anything.'
    )

    monday    = models.BooleanField()
    tuesday   = models.BooleanField()
    wednesday = models.BooleanField()
    thursday  = models.BooleanField()
    friday    = models.BooleanField()
    saturday  = models.BooleanField()
    sunday    = models.BooleanField()

    turn_on_task = models.OneToOneField(
        PeriodicTask,
        editable=False,
        on_delete=models.PROTECT,
        related_name='alarm_schedule_on'
    )

    turn_off_task = models.OneToOneField(
        PeriodicTask,
        editable=False,
        on_delete=models.PROTECT,
        related_name='alarm_schedule_off'
    )

    alarm_statuses = models.ManyToManyField(
        AlarmStatus,
        related_name='alarm_schedules',
        help_text='List of alarm statuses to impact.'
    )

    def delete(self, *args, **kwargs):
        with transaction.atomic():
            super().delete(*args, **kwargs)

            if self.turn_off_task:
                self.turn_off_task.delete()

            if self.turn_on_task:
                self.turn_on_task.delete()

    def get_absolute_url(self):
        return reverse('alarm:schedule-detail', args=[str(self.id)])

core/app/alarm/forms.py
from django.forms.widgets import DateTimeInput
from alarm.use_cases.alarm_schedule_range import create_alarm_schedule_range, update_alarm_schedule_range
from alarm.use_cases.alarm_schedule import create_alarm_schedule, update_alarm_schedule
from django import forms
from django.db import transaction
from alarm.use_cases.alarm_status import AlarmChangeStatus
from alarm.models import AlarmSchedule, AlarmScheduleDateRange, AlarmStatus


class FormInformation():
    _creating: bool

    def __init__(self, *args, **kwargs):
        self._creating = kwargs.get('instance') is None
        super().__init__(*args, **kwargs)

    @property
    def is_creating(self) -> bool:
        return self._creating


class AlarmRangeScheduleForm(FormInformation, forms.ModelForm):

    class Meta:
        model = AlarmScheduleDateRange
        fields = '__all__'
        widgets = {
            'datetime_start': DateTimeInput(
                attrs={'type': 'datetime-local'},
                format="%Y-%m-%dT%H:%M"
            ),
            'datetime_end': DateTimeInput(
                attrs={'type': 'datetime-local'},
                format="%Y-%m-%dT%H:%M"
            ),
        }

    def save(self, commit: bool = True) -> AlarmScheduleDateRange:
        instance = super().save(commit=False)

        if self.is_creating:
            self.instance = create_alarm_schedule_range(instance)
        else:
            self.instance = update_alarm_schedule_range(instance)

        return self.instance

class AlarmScheduleForm(FormInformation, forms.ModelForm):

    class Meta:
        model = AlarmSchedule
        fields = '__all__'

    def save(self, commit: bool = True) -> AlarmSchedule:
        instance = super().save(commit=False)

        if self.is_creating:
            self.instance = create_alarm_schedule(instance)
        else:
            self.instance = update_alarm_schedule(instance)

        self.save_m2m()

        return self.instance


class AlarmStatusForm(forms.ModelForm):
    class Meta:
        model = AlarmStatus
        fields = ['running']

    def save(self, commit: bool = True) -> AlarmStatus:
        instance = super().save(commit=False)
        AlarmChangeStatus().save_status(instance)
        return instance

core/app/alarm/views/alarm_status_views.py
from alarm.forms import AlarmScheduleForm, AlarmStatusForm
from typing import List

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, UpdateView, DetailView, TemplateView
from django.views.generic.edit import CreateView
from django.forms import ModelForm

from alarm.business.alarm_schedule import DAYS_OF_WEEK
from alarm.use_cases.alarm_status import AlarmChangeStatus
from alarm.models import AlarmStatus, AlarmSchedule
from devices.models import Device
from utils.django.forms import ChangeForm
from utils.django.json_view import JsonableResponseMixin
from utils.views import HTMLFormMessageFieldBased


class AlarmHome(LoginRequiredMixin, TemplateView):
    template_name = "alarm/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        alarms: List[AlarmStatus] = AlarmStatus.objects.select_related('device__location').order_by('device__device_id').prefetch_related('alarm_schedules')
        context['alarms'] = alarms

        return context


class AlarmStatusCreate(LoginRequiredMixin, ChangeForm, CreateView):
    model = AlarmStatus
    fields = '__all__'

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        # Device -> Alarm is a OneToOne relationship.
        # If a device is already linked to an alarm status, don't propose it through the form.
        form.fields['device'].queryset = Device.objects.filter(alarmstatus=None)
        return form

    def form_valid(self, form):
        res = super().form_valid(form)
        # alarm_status_changed(self.object)
        return res


class AlarmStatusUpdate(LoginRequiredMixin, JsonableResponseMixin, ChangeForm, UpdateView):
    form_class = AlarmStatusForm
    model = AlarmStatus
    template_name = 'alarm/status_form.html'
    success_url = reverse_lazy('alarm:home')
    context_object_name = 'alarm'
    queryset = AlarmStatus.objects.with_device_and_location()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        formOptions = HTMLFormMessageFieldBased(
            trueSuccess='Your alarm is now on.',
            falseSuccess='Your alarm is now off.',
            statusField='running',
            isCustomForm=True
        )

        context['formOptions'] = formOptions

        return context


class AlarmStatusDetail(LoginRequiredMixin, DetailView):
    model = AlarmStatus
    template_name = 'alarm/alarm_detail.html'
    context_object_name = 'alarm'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # alarm_status: AlarmStatus = context[self.context_object_name]

        context['DAYS_OF_WEEK'] = DAYS_OF_WEEK

        return context

class AlarmScheduleUpdate(LoginRequiredMixin, ChangeForm, UpdateView):
    form_class = AlarmScheduleForm
    model = AlarmSchedule

    def get_success_url(self):
        return reverse('alarm:schedule-detail', args=(self.object.id,))


class AlarmScheduleCreate(LoginRequiredMixin, ChangeForm, CreateView):
    form_class = AlarmScheduleForm
    model = AlarmSchedule


class AlarmScheduleDetail(DetailView):
    model = AlarmSchedule
    context_object_name = 'schedule'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # alarm_status: AlarmStatus = context[self.context_object_name]

        context['DAYS_OF_WEEK'] = DAYS_OF_WEEK

        return context

core/app/alarm/views/schedule_range_views.py
from django.urls.base import reverse
from django.views.generic.detail import DetailView
from alarm.forms import AlarmRangeScheduleForm
from alarm.models import AlarmScheduleDateRange
from django.contrib.auth.mixins import LoginRequiredMixin
from utils.django.forms import ChangeForm
from django.views.generic.edit import CreateView, UpdateView


class AlarmScheduleRangeWrite(LoginRequiredMixin, ChangeForm):
    form_class = AlarmRangeScheduleForm
    model = AlarmScheduleDateRange

    def get_success_url(self):
        return reverse('alarm:absence-detail', kwargs={'pk': self.object.pk})


class AlarmScheduleRangeCreate(AlarmScheduleRangeWrite, CreateView):
    pass


class AlarmScheduleRangeUpdate(AlarmScheduleRangeWrite, UpdateView):
    pass


class AlarmScheduleRangeDetail(LoginRequiredMixin, DetailView):
    model = AlarmScheduleDateRange

core/app/templates/alarm/alarm_detail.html
{% extends '_layout.html' %}
{% load i18n %}

{% block body %}
    <main class="l-container">
        <section class="l-section l-row">
            <div class="copy variant--content variant--box">
                <div class="copy__body l-stack">
                    <div class="l-stack-bottom-separator">
                        <h3 class="h5">{% trans 'Alarm information' %}</h3>
                    </div>
                    <div class="copy__body l-stack">
                        {% with see_schedules=False %}
                            {% include 'partials/_alarm_status_info.html' %}
                        {% endwith %}
                    </div>
                </div>
            </div>

            {% if alarm.alarm_schedules.all %}
                <h2 class="h4">
                    {% trans 'Schedules' %}
                </h2>

                {% with see_more=True %}
                    {% for schedule in alarm.alarm_schedules.all %}
                        {% include 'partials/_alarm_schedule_info.html' %}
                    {% endfor %}
                {% endwith %}
            {% endif %}
        </section>
    </main>

{% endblock body %}

core/app/templates/alarm/alarmschedule_detail.html
{% extends '_layout.html' %}
{% load i18n %}

{% block body %}
    <main class="l-container">
        <section class="l-section l-row">
            {% with box_title='Schedule information' %}
                {% include 'partials/_alarm_schedule_info.html' %}
            {% endwith %}
            <h2 class="h4">
                {% trans 'List of linked alarms' %}
            </h2>

            {% include 'partials/_alarm_list.html' with alarms=schedule.alarm_statuses.all %}
        </section>
    </main>

{% endblock body %}

core/app/templates/alarm/alarmscheduledaterange_detail.html
{% extends '_layout.html' %}
{% load i18n %}

{% block body %}
    <main class="l-container">
        <section class="l-section l-row">
            <div class="copy variant--content variant--box">
                <div class="copy__body l-stack">
            
                    <div class="l-stack-bottom-separator">
                        <h3 class="h5">Absence mode</h3>
                    </div>
            
                    <p class="flex items-center">
                        {% svg_icon 'shield' %}
                        <span class="l-ml1">Alarm turns on from {{ object.datetime_start }}
                            {% if object.datetime_end %}
                                to {{ object.datetime_end }}
                            {% endif %}
                        </span>
                    </p>
                </div>
            </div> 
        </section>
    </main>

{% endblock body %}

core/app/templates/alarm/home.html
{% extends '_layout.html' %}
{% load i18n %}

{% block body %}
    <div class="l-container">
        <div class="l-section l-row">

            <div class="flex justify-between items-center wrap gap-1">
                <h2 class="h4">{% trans 'Your alarms' %}</h2>

                <div>
                    <a class="btn-secondary" href="{% url 'alarm:absence-add' %}">
                        {% svg_icon 'plus' 'left' %}
                        <span>
                            {% trans 'Absence mode' %}
                        </span>
                    </a>
                    <a class="btn-secondary" href="{% url 'alarm:status-add' %}">
                        {% svg_icon 'plus' 'left' %}
                        <span>
                            {% trans 'New alarm' %}
                        </span>
                    </a>
                </div>
            </div>
            {% include 'partials/_alarm_list.html' %}
        </div>
    </div>
{% endblock body %}

core/app/templates/alarm/schedule.html
{% extends '_layout.html' %}

{% block header %}
    <h1 class="h3">Schedule alarm</h1>
{% endblock header %}

{% block body %}
    <main class="l-container">
        <div class="box">
            <div class="box__body">
                <form action="" method="post">
                    {{ csrf_input }}
                    {{ form }}
                    <input type="submit" value="Submit">
                </form>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi aliquam animi odio, reprehenderit corporis repellat! Quibusdam, fuga nam enim earum facilis veniam minima natus quasi accusamus recusandae debitis hic cupiditate?</p>
            </div>
        </div>
    </main>
{% endblock body %}

core/app/templates/alarm/status_form.html
{% extends 'generics/_change_form.html' %}

{% load i18n %}

{% block form_header %}
    {% include 'partials/_alarm_status_info.html' %}
{% endblock %}


{##}
{#{% block body %}#}
{##}
{#    <main class="l-container">#}
{#        <section class="l-section">#}
{#            <div class="copy variant--content variant--box">#}
{#                <div class="copy__body l-stack">#}
{#                    <section class="l-stack l-stack-bottom-separator">#}
{#                        {% if object %}#}
{#                            <h2 class="h5">{% trans 'Change alarm status' %}</h2>#}
{#                            {% include 'partials/_alarm_status_info.html' %}#}
{#                        {% else %}#}
{#                            <h2 class="h5">{% trans 'Create alarm status' %}</h2>#}
{#                        {% endif %}#}
{#                    </section>#}
{#                    <form is="custom-form" action="" method="post" class="l-stack vertical-form"#}
{#                          data-dialog=""#}
{#                          data-dialog-title="{% trans 'Do you really want to change the status of your alarm?' %}"#}
{#                          data-dialog-content="{% trans 'This will stop or run your alarm immediately!' %}"#}
{#                          data-true-success="{% trans 'Your alarm is now on.' %}"#}
{#                          data-false-success="{% trans 'Your alarm is now off.' %}"#}
{#                          data-status-field="running"#}
{#                    >#}
{#                        {% include "partials/_form.html" %}#}
{#                        {% include "partials/_form_actions.html" with btn_text="Save" %}#}
{#                    </form>#}
{#                </div>#}
{#            </div>#}
{#        </section>#}
{#    </main>#}
{##}
{#{% endblock body %}#}